### ISSUE TITLE
Preview failed

### ISSUE THREAD

**Issue by vivadavid** [Cologler/QuickLook.Plugin.TorrentViewer#5]
Hi,

I've installed the plugin in my computer with Windows 11 and QuickLook keeps displaying an error message: "Preview failed". It worked perfectly well when my PC ran Windows 10. My QuickLook version is 3.7.1. Thanks.

**Comment by alexhua** [comment]
See https://github.com/Cologler/QuickLook.Plugin.TorrentViewer/blob/master/README.md

**Comment by vivadavid** [comment]
Thank you! Actually, I've just realized that I did that the first time I installed the plugin, but then I forgot about it. My fault! Sorry!
