### ISSUE TITLE
Where to put code in readme

### ISSUE THREAD

**Issue by albertopasqualetto** [Cologler/QuickLook.Plugin.TorrentViewer#6]
Hello, I do not have `QuickLook.exe.config`, but only `QuickLook.config`, because, I think, I am using the store version of the app.
Besides this, i do not already have the tag "configuration", but only the "Settings" one, so I do not know where to put the code.
Thanks.

**Comment by Cologler** [comment]
Should be `C:\Program Files\WindowsApps\21090PaddyXu.QuickLook_3.7.1.0_neutral__egxr34yet59cg\Package\QuickLook.exe.config`

**Comment by albertopasqualetto** [comment]
Ok, I found it, now I cannot modify that file, but I will try to do it.
In anycase I suggest you to write more specifically where to find that file.
