### ISSUE TITLE
No Permission error while modifying quicklook.exe.config file

### ISSUE THREAD

**Issue by Xx-Mohit-xX** [Cologler/QuickLook.Plugin.TorrentViewer#7]
I tried editing the file but i couldn't save it. tried different ways such as editing it through vsc or even through terminal with administrative perms but no luck.

Anyone knows a fix?

**Comment by Cologler** [comment]
Are you using the Microsoft Store version of QuickLook?

**Comment by Xx-Mohit-xX** [comment]
yes Indeed

**Comment by Cologler** [comment]
Close as duplicate (#3).
