### ISSUE TITLE
Error Preview Failed

### ISSUE THREAD

**Issue by jmlv5** [Cologler/QuickLook.Plugin.TorrentViewer#8]
![image](https://user-images.githubusercontent.com/67466481/232992256-7061ff68-d61d-4f0c-9e30-b4b36c84ecdf.png)

When I try to preview a .torrent always show this message...

**Comment by Cologler** [comment]
Please read the README document.

**Comment by jmlv5** [comment]
oohhh sorry! then my problem is the same as #7 can't edit this file....system permissions needed....I don't know what this means...
